export const ACTION="ACTION"

export const LOGIN_USER="LOGIN_USER"
export const LOGIN_STUDENT="LOGIN_STUDENT"
export const GET_AUTH_USER="GET_AUTH_USER"
export const LOGOUT="LOGOUT"

export const REGISTER_STUDENT="REGISTER_STUDENT"
export const GET_STUDENTS="GET_STUDENTS"
export const EDITE_STUDENT="EDITE_STUDENT"

export const REGISTER_CLUB="REGISTER_CLUB"
export const GET_CLUBS="GET_CLUBS"
export const EDITE_CLUB="EDITE_CLUB"

export const AUTH_ERROR="AUTH_ERROR"

export const SET_LOADING="SET_LOADING"